line-length = 100
target-version = "py311"

[lint]
select = ["E", "F", "B", "I"]
ignore = ["E203"]
exclude = [
  "migrations",
  "**/.venv",
  "**/venv",
  "**/__pycache__",
  "build",
  "dist",
]

[lint.isort]
combine-as-imports = true
known-first-party = ["accounts", "hr", "reviews", "wellbeing", "smarthr360_backend"]
